# Generated by Django 4.0 on 2021-12-09 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueConscripts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('dar', 'Дарницький військовий комісаріат'), ('dec', 'Деснянський військовий комісаріат'), ('dni', 'Дніпровський військовий комісаріат')], max_length=3)),
                ('week_day', models.CharField(choices=[('tu', 'tuesday'), ('th', 'thursday')], max_length=2)),
                ('time', models.CharField(max_length=20)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
