# Generated by Django 4.0 on 2021-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_queueconscripts_delete_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueconscripts',
            name='busy',
            field=models.CharField(choices=[('', 'Вільно'), ('Зайнято', 'Зайнято')], default='Вільно', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
